# Generated by Django 5.0.2 on 2024-03-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('is_toxic', models.BooleanField(null=True)),
            ],
        ),
    ]
