# Generated by Django 5.0.2 on 2024-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_toxic",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="video_id",
            field=models.CharField(max_length=255),
        ),
    ]
